from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, DECIMAL, JSON, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.models.base import BaseModel

class Alert(BaseModel):
    """
    Represents an alert generated by the system for a user.
    """
    __tablename__ = "alerts"

    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    type = Column(String, nullable=False) # low_stock, low_margin, price_drop, policy_trigger
    product_id = Column(Integer, ForeignKey("products.id"), nullable=True)
    listing_id = Column(Integer, ForeignKey("listings.id"), nullable=True)
    severity = Column(String, default="info", nullable=False) # info, warning, critical
    message = Column(Text, nullable=False)
    data = Column(JSON, nullable=True) # JSONB, context data
    is_read = Column(Boolean, default=False, nullable=False)
    read_at = Column(DateTime(timezone=True), nullable=True)
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)

    user = relationship("User", backref="alerts")
    product = relationship("Product", backref="alerts")
    listing = relationship("Listing", backref="alerts")

class Job(BaseModel):
    """
    Represents a background job executed by the system.
    """
    __tablename__ = "jobs"

    user_id = Column(Integer, ForeignKey("users.id"), nullable=True) # Nullable for system jobs
    type = Column(String, nullable=False) # scrape_amazon, track_products, sync_ebay, upload_shopify
    status = Column(String, default="PENDING", nullable=False) # PENDING, RUNNING, SUCCESS, FAILED, CANCELLED
    params = Column(JSON, nullable=True) # JSONB, input data {asin, product_id, etc}
    result = Column(JSON, nullable=True) # JSONB, output {product_id, error, etc}
    error_message = Column(Text, nullable=True)
    retry_count = Column(Integer, default=0, nullable=False)
    started_at = Column(DateTime(timezone=True), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    next_retry_at = Column(DateTime(timezone=True), nullable=True)

    user = relationship("User", backref="jobs")

class ProxyPool(BaseModel):
    """
    Represents a proxy server available for scraping.
    """
    __tablename__ = "proxy_pool"

    host = Column(String, nullable=False)
    port = Column(Integer, nullable=False)
    username = Column(String, nullable=True)
    password = Column(String, nullable=True) # encrypted
    protocol = Column(String, nullable=False) # http, socks5
    country = Column(String, nullable=True)
    health_score = Column(Integer, default=100, nullable=False) # 0-100
    success_count = Column(Integer, default=0, nullable=False)
    failure_count = Column(Integer, default=0, nullable=False)
    last_checked_at = Column(DateTime(timezone=True), nullable=True)
    last_failed_at = Column(DateTime(timezone=True), nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)

class AnalyticsCache(BaseModel):
    """
    Stores pre-calculated analytics data for faster retrieval.
    """
    __tablename__ = "analytics_cache"

    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    metric_type = Column(String, nullable=False) # total_revenue, total_profit, top_products, etc
    time_period = Column(String, nullable=False) # daily, weekly, monthly
    data = Column(JSON, nullable=False) # JSONB, complex calculated data
    computed_at = Column(DateTime(timezone=True), nullable=False)
    expires_at = Column(DateTime(timezone=True), nullable=True) # for TTL

    user = relationship("User", backref="analytics_cache")

class AuditLog(BaseModel):
    """
    Records significant actions performed by users or the system.
    """
    __tablename__ = "audit_log"

    user_id = Column(Integer, ForeignKey("users.id"), nullable=True) # Nullable for system actions
    action = Column(String, nullable=False) # created, updated, deleted, paused, resumed
    resource_type = Column(String, nullable=False) # product, listing, store_account
    resource_id = Column(Integer, nullable=False)
    old_value = Column(JSON, nullable=True) # JSONB, what changed
    new_value = Column(JSON, nullable=True) # JSONB, to what
    ip_address = Column(String, nullable=True)
    user_agent = Column(String, nullable=True)
    timestamp = Column(DateTime(timezone=True), server_default=func.now())
    notes = Column(Text, nullable=True)

    user = relationship("User", backref="audit_logs")

class Notification(BaseModel):
    """
    Represents a notification to be sent to a user.
    """
    __tablename__ = "notifications"

    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    type = Column(String, nullable=False) # alert, policy_trigger, job_complete, report
    recipient = Column(String, nullable=False) # email, sms, webhook
    subject = Column(String, nullable=True)
    body = Column(JSON, nullable=False) # JSONB or text
    is_sent = Column(Boolean, default=False, nullable=False)
    sent_at = Column(DateTime(timezone=True), nullable=True)
    metadata_ = Column("metadata", JSON, nullable=True) # JSONB, using metadata_ to avoid keyword conflict

    user = relationship("User", backref="notifications")
